"""HTML report generator for TestMind test runs.

Reads the ``summary.json`` and per-case ``*.json`` files written by
:func:`Runner._save_results` and produces a self-contained
``report.html`` alongside them.  The report is a single static file
(no external CSS/JS dependencies) so it can be emailed, attached to a
CI artifact, or opened directly from the filesystem.

Design choices:

* **Pure Python string templating** — no Jinja2 dependency for the
  report body.  The report is simple enough that ``str.format`` with a
  few helpers is clearer than adding a template engine.
* **Offline & self-contained** — all styling is inline.  The file
  works without a network connection and without a web server.
* **ASCII safety** — the generated HTML uses UTF-8, but status icons
  are textual labels (PASS/FAIL/ERR/SKIP) to stay consistent with the
  terminal output.
"""

from __future__ import annotations

import html
import json
from datetime import datetime
from pathlib import Path
from typing import Any


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------


def generate_html_report(results_dir: str | Path) -> str:
    """Generate ``report.html`` inside *results_dir* and return its path.

    *results_dir* must contain a ``summary.json`` and zero or more
    per-case ``<case_id>.json`` files (as written by
    :func:`Runner._save_results`).  Missing files are skipped silently
    so a partial run still yields a report.

    Args:
        results_dir: Path to the run's results directory.

    Returns:
        The absolute path to the generated ``report.html``.

    Raises:
        FileNotFoundError: If ``summary.json`` does not exist.
    """
    results_dir = Path(results_dir)
    summary_path = results_dir / "summary.json"
    if not summary_path.is_file():
        raise FileNotFoundError(f"summary.json not found in {results_dir}")

    summary = json.loads(summary_path.read_text(encoding="utf-8"))
    cases = _load_case_results(results_dir)

    html_content = _render_html(summary, cases)
    report_path = results_dir / "report.html"
    report_path.write_text(html_content, encoding="utf-8")
    return str(report_path)


# ---------------------------------------------------------------------------
# Internal helpers
# ---------------------------------------------------------------------------


def _load_case_results(results_dir: Path) -> list[dict[str, Any]]:
    """Load all per-case result JSON files from *results_dir*.

    Skips ``summary.json``, ``report.html``, and any ``*_retry_*.json``
    retry artifacts (those are detail files, not top-level case
    results).
    """
    cases: list[dict[str, Any]] = []
    for f in sorted(results_dir.glob("*.json")):
        if f.name == "summary.json":
            continue
        if "_retry_" in f.stem:
            continue
        try:
            cases.append(json.loads(f.read_text(encoding="utf-8")))
        except (json.JSONDecodeError, OSError):
            continue
    return cases


def _render_html(summary: dict[str, Any], cases: list[dict[str, Any]]) -> str:
    """Render the full HTML document as a string."""
    pass_rate = _pass_rate(summary)
    css = _CSS
    header = _render_header(summary, pass_rate)
    summary_cards = _render_summary_cards(summary, pass_rate)
    failures_section = _render_failures_section(summary)
    cases_table = _render_cases_table(cases)

    generated_at = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

    return f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>TestMind Report - {html.escape(summary.get('run_id', ''))}</title>
<style>{css}</style>
</head>
<body>
{header}
{summary_cards}
{failures_section}
{cases_table}
<footer>
  Generated by TestMind at {html.escape(generated_at)}
</footer>
</body>
</html>
"""


def _pass_rate(summary: dict[str, Any]) -> float:
    total = summary.get("total", 0)
    if total <= 0:
        return 0.0
    return round(summary.get("passed", 0) / total * 100, 1)


def _render_header(summary: dict[str, Any], pass_rate: float) -> str:
    run_id = html.escape(summary.get("run_id", ""))
    project = html.escape(summary.get("project", ""))
    env = html.escape(summary.get("env", ""))
    started = html.escape(summary.get("started_at", ""))
    finished = html.escape(summary.get("finished_at", ""))
    rate_class = "pass" if pass_rate >= 100 else "warn" if pass_rate >= 50 else "fail"
    return f"""
<header>
  <h1>TestMind Run Report</h1>
  <div class="meta">
    <span><strong>Run ID:</strong> {run_id}</span>
    <span><strong>Project:</strong> {project}</span>
    <span><strong>Env:</strong> {env}</span>
    <span><strong>Started:</strong> {started}</span>
    <span><strong>Finished:</strong> {finished}</span>
  </div>
  <div class="pass-rate {rate_class}">Pass Rate: {pass_rate}%</div>
</header>
"""


def _render_summary_cards(summary: dict[str, Any], pass_rate: float) -> str:
    cards = [
        ("Total", summary.get("total", 0), "total"),
        ("Passed", summary.get("passed", 0), "pass"),
        ("Failed", summary.get("failed", 0), "fail"),
        ("Error", summary.get("error", 0), "error"),
        ("Skipped", summary.get("skipped", 0), "skipped"),
        ("Duration", f"{summary.get('total_duration_ms', 0)} ms", "duration"),
    ]
    card_html = "\n".join(
        f'    <div class="card {cls}"><div class="card-value">{val}</div><div class="card-label">{label}</div></div>'
        for label, val, cls in cards
    )
    return f"""
<section class="summary">
  <h2>Summary</h2>
  <div class="cards">
{card_html}
  </div>
</section>
"""


def _render_failures_section(summary: dict[str, Any]) -> str:
    failures = summary.get("failures", []) or []
    errors = summary.get("errors", []) or []
    if not failures and not errors:
        return ""
    rows = []
    for f in failures:
        rows.append(
            f"      <tr class='fail'><td>{html.escape(str(f.get('case_id', '')))}</td>"
            f"<td>FAIL</td><td>{html.escape(str(f.get('reason', '')))}</td></tr>"
        )
    for e in errors:
        rows.append(
            f"      <tr class='error'><td>{html.escape(str(e.get('case_id', '')))}</td>"
            f"<td>ERROR</td><td>{html.escape(str(e.get('reason', '')))}</td></tr>"
        )
    rows_html = "\n".join(rows)
    return f"""
<section class="failures">
  <h2>Failures & Errors</h2>
  <table>
    <thead><tr><th>Case ID</th><th>Status</th><th>Reason</th></tr></thead>
    <tbody>
{rows_html}
    </tbody>
  </table>
</section>
"""


def _render_cases_table(cases: list[dict[str, Any]]) -> str:
    if not cases:
        return """
<section class="cases">
  <h2>Case Details</h2>
  <p>No case result files found.</p>
</section>
"""
    rows = []
    for c in cases:
        status = c.get("status", "?")
        case_id = html.escape(c.get("case_id", ""))
        dur = c.get("duration_ms", 0)
        env = html.escape(c.get("env", ""))
        err = html.escape(str(c.get("error") or ""))
        method = ""
        url = ""
        status_code = ""
        req = c.get("request_snapshot") or {}
        resp = c.get("response_snapshot") or {}
        if req:
            method = html.escape(req.get("method", ""))
            url = html.escape(req.get("url", ""))
        if resp:
            status_code = resp.get("status_code", "")
        assertions = c.get("assertions_result") or []
        passed_a = sum(1 for a in assertions if a.get("passed"))
        total_a = len(assertions)
        assertions_summary = f"{passed_a}/{total_a}" if total_a else "-"

        rows.append(
            f"      <tr class='{status}'>"
            f"<td>{case_id}</td><td><span class='badge {status}'>{status.upper()}</span></td>"
            f"<td>{env}</td><td>{method}</td><td class='url'>{url}</td>"
            f"<td>{status_code}</td><td>{dur} ms</td>"
            f"<td>{assertions_summary}</td><td class='err'>{err}</td></tr>"
        )
    rows_html = "\n".join(rows)
    return f"""
<section class="cases">
  <h2>Case Details</h2>
  <table>
    <thead><tr>
      <th>Case ID</th><th>Status</th><th>Env</th><th>Method</th><th>URL</th>
      <th>HTTP</th><th>Duration</th><th>Assertions</th><th>Error</th>
    </tr></thead>
    <tbody>
{rows_html}
    </tbody>
  </table>
</section>
"""


# ---------------------------------------------------------------------------
# CSS (inline, self-contained)
# ---------------------------------------------------------------------------


_CSS = """
* { box-sizing: border-box; }
body {
  font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif;
  margin: 0; padding: 24px; background: #f5f6fa; color: #2d3436;
}
header { background: #fff; padding: 24px 32px; border-radius: 8px; margin-bottom: 16px;
  box-shadow: 0 1px 3px rgba(0,0,0,0.08); }
header h1 { margin: 0 0 12px 0; font-size: 24px; }
.meta { display: flex; flex-wrap: wrap; gap: 24px; font-size: 14px; color: #636e72; }
.meta span { display: inline-block; }
.pass-rate { margin-top: 16px; font-size: 28px; font-weight: 700; }
.pass-rate.pass { color: #00b894; }
.pass-rate.warn { color: #fdcb6e; }
.pass-rate.fail { color: #d63031; }
section { background: #fff; padding: 20px 24px; border-radius: 8px; margin-bottom: 16px;
  box-shadow: 0 1px 3px rgba(0,0,0,0.08); }
section h2 { margin: 0 0 16px 0; font-size: 18px; border-bottom: 2px solid #dfe6e9;
  padding-bottom: 8px; }
.cards { display: flex; flex-wrap: wrap; gap: 16px; }
.card { flex: 1 1 120px; padding: 16px; border-radius: 6px; text-align: center;
  background: #f5f6fa; border-left: 4px solid #b2bec3; }
.card.pass { border-left-color: #00b894; }
.card.fail { border-left-color: #d63031; }
.card.error { border-left-color: #fdcb6e; }
.card.skipped { border-left-color: #74b9ff; }
.card.total, .card.duration { border-left-color: #636e72; }
.card-value { font-size: 28px; font-weight: 700; }
.card-label { font-size: 12px; color: #636e72; text-transform: uppercase; letter-spacing: 0.5px; }
table { width: 100%; border-collapse: collapse; font-size: 13px; }
th, td { text-align: left; padding: 8px 12px; border-bottom: 1px solid #dfe6e9; }
th { background: #f5f6fa; font-weight: 600; text-transform: uppercase; font-size: 11px;
  letter-spacing: 0.5px; color: #636e72; }
tr.pass { background: #e6ffed; }
tr.fail { background: #ffeef0; }
tr.error { background: #fff8e1; }
tr.skipped { background: #f0f7ff; }
tr:hover { background: #fff; }
.badge { padding: 2px 8px; border-radius: 4px; font-size: 11px; font-weight: 700; }
.badge.pass { background: #00b894; color: #fff; }
.badge.fail { background: #d63031; color: #fff; }
.badge.error { background: #fdcb6e; color: #2d3436; }
.badge.skipped { background: #74b9ff; color: #fff; }
.url { max-width: 300px; overflow: hidden; text-overflow: ellipsis; white-space: nowrap;
  font-family: monospace; font-size: 12px; }
.err { max-width: 250px; overflow: hidden; text-overflow: ellipsis; white-space: nowrap;
  color: #d63031; font-size: 12px; }
footer { text-align: center; color: #b2bec3; font-size: 12px; padding: 24px 0; }
@media print {
  body { background: #fff; }
  section, header { box-shadow: none; }
}
"""
